name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up MSYS2 for building with g++
      - name: Install MSYS2 and g++
        run: |
          choco install msys2
          pacman -Syu --noconfirm
          pacman -S mingw-w64-x86_64-gcc --noconfirm

      # Build the project
      - name: Build the project
        run: |
          g++ ./src/scfg.cpp -I./src/include -L./src/ -llua54 -o scfg.exe -std=c++23 -static
          if ($?) {
            Write-Host "Build successful"
            ls -al  # 输出当前目录的文件列表
          } else {
            Write-Host "Build failed"
            exit 1
          }
