name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up MSYS2 for building with g++
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          version: 12.2.0 
          platform: x64

      # Build the project
      - name: Build the project
        run: |
          g++ ./src/scfg.cpp -I./src/include -L./src/ -llua54 -o scfg.exe -std=c++23 -static -fcoroutines
          if ($?) {
            Write-Host "Build successful"
          } else {
            Write-Host "Build failed"
            exit 1
          }
          
      # Upload the build artifact (scfg.exe) to the release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: scfg
          path: scfg.exe

  release:
    needs: build
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Create GitHub release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: scfg.exe
